"""food column rename

Revision ID: 8ba01f4efdc4
Revises: 2521fc20a9e7
Create Date: 2022-08-18 08:11:24.233451

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8ba01f4efdc4'
down_revision = '2521fc20a9e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('food_name', sa.String(), nullable=False))
    op.drop_column('foods', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('foods', 'food_name')
    # ### end Alembic commands ###
