"""when_unique

Revision ID: abcb8d2eaa26
Revises: ff19a05cc7b4
Create Date: 2022-08-18 18:25:45.699245

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'abcb8d2eaa26'
down_revision = 'ff19a05cc7b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'logs', ['when'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='unique')
    # ### end Alembic commands ###
