"""lazy foods loading

Revision ID: ead7473d23b1
Revises: abcb8d2eaa26
Create Date: 2022-08-20 19:23:47.562738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead7473d23b1'
down_revision = 'abcb8d2eaa26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
