"""food_name-unique

Revision ID: ff19a05cc7b4
Revises: 8ba01f4efdc4
Create Date: 2022-08-18 11:43:27.361902

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff19a05cc7b4'
down_revision = '8ba01f4efdc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'foods', ['food_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'foods', type_='unique')
    # ### end Alembic commands ###
